version: 0.1.0

project: navigation2-ignition-example

jobs:

  all: # Overall job name
    type: test
    package:
      custom:
        commands:
        - apt update && apt install -y ros-humble-navigation2 ros-humble-nav2-bringup
        - pip install vcstool
        - vcs import --input /ws/src/deps.repos src/src
    runtime:
      simulator: gazebo:fortress
      framework: ros2:humble
    timeout: 5 #minutes
    scenarios:
      defaults: # Global to all scenarios, and overriden in specific scenarios.
        subscriptions:
          rosout: rosout
        launch_arguments:
          run_headless: true
      settings:
        - name: bringup
          ros_testfile: "src/sam_bot_nav2_gz/test/test_bringup.launch.py"
        - name: reach_goal
          ros_testfile: "src/sam_bot_nav2_gz/test/test_reach_goal.launch.py"
        - name: follow_waypoints
          ros_testfile: "src/sam_bot_nav2_gz/test/test_follow_waypoints.launch.py"
