version: 0.1.0

project: artefacts/navigation2-ignition-example

jobs:
  nav2:
    type: test
    package:
      docker:
        build:
          dockerfile: ./docker/Dockerfile
    runtime:
      simulator: gazebo:fortress
      framework: null
    timeout: 5 #minutes
    scenarios:
      defaults: # Global to all scenarios, and overriden in specific scenarios.
        output_dirs: ["output"]
        metrics:
          - /odometry_error
          - /distance_from_start_gt
          - /distance_from_start_est
        params:
          launch/world: "empty.sdf"
      settings:
        # - name: reach_goal
        #   ros_testfile: "src/sam_bot_nav2_gz/test/test_reach_goal.launch.py"
        - name: follow_waypoints
          run: python3 -m pytest src/sam_bot_nav2_gz/test/test_follow_waypoints.py --html=output/report.html --self-contained-html
